### PR TITLE
added zuul support

### PR DESCRIPTION
**Pull request by fredericlepied**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
@sduthil dunno what to do with this one, is it even used ?

**Comment by sduthil** [comment]
Oh yes, definitely used: every Wazo service needs it to register into Consul.

**Comment by sduthil** [comment]
I'm on it, I'll remove the Python2 version that is failing and not used.

**Review by sduthil — APPROVED** [review]

**Pull request merged**
